// Compact personal-use filter lists for the Aura VPN browser extension.
// Add more domains/selectors here as needed; keep entries lowercase.

export const FILTER_CATEGORIES = {
  ads: {
    label: "광고 차단",
    description: "광고 스크립트·iframe·배너 요청을 차단하고 광고 영역을 숨깁니다.",
    defaultOn: true,
  },
  trackers: {
    label: "추적기 차단",
    description: "방문 분석·추적 픽셀 요청을 차단합니다.",
    defaultOn: true,
  },
  annoyances: {
    label: "팝업·오버레이 차단",
    description: "팝업·모달·쿠키 배너처럼 고정된 방해 요소를 숨깁니다.",
    defaultOn: false,
  },
};

export const AD_HOSTS = [
  "1rx.io",
  "2mdn.net",
  "33across.com",
  "ad-maven.com",
  "adblade.com",
  "adbutler.com",
  "adcash.com",
  "adcolony.com",
  "adform.net",
  "adhigh.net",
  "adition.com",
  "adkernel.com",
  "admanmedia.com",
  "adnxs.com",
  "adreactor.com",
  "adroll.com",
  "adsafeprotected.com",
  "adscendmedia.com",
  "adsrvr.org",
  "adsterra.com",
  "adsymptotic.com",
  "adtechus.com",
  "adtelligent.com",
  "advertising.com",
  "adyoulike.com",
  "adzerk.net",
  "amazon-adsystem.com",
  "applovin.com",
  "appnexus.com",
  "bidr.io",
  "bidswitch.net",
  "bidtheatre.com",
  "brightroll.com",
  "bttrack.com",
  "casalemedia.com",
  "cedato.com",
  "chartboost.com",
  "clickadu.com",
  "connatix.com",
  "contentabc.com",
  "criteo.com",
  "criteo.net",
  "dianomi.com",
  "districtm.io",
  "doubleclick.net",
  "dsply.com",
  "emxdgt.com",
  "exoclick.com",
  "freewheel.tv",
  "fyber.com",
  "googleadservices.com",
  "googlesyndication.com",
  "googletagservices.com",
  "gumgum.com",
  "hilltopads.net",
  "indexww.com",
  "inmobi.com",
  "insticator.com",
  "ironsrc.mobi",
  "juicyads.com",
  "kargo.com",
  "leadbolt.net",
  "lijit.com",
  "lockerdome.com",
  "mathtag.com",
  "media.net",
  "mgid.com",
  "millennial.com",
  "mintegral.com",
  "moatads.com",
  "mopub.com",
  "nativo.com",
  "onclasrv.com",
  "openx.net",
  "outbrain.com",
  "playwire.com",
  "plista.com",
  "popads.net",
  "popcash.net",
  "propellerads.com",
  "pubmatic.com",
  "revcontent.com",
  "rhythmone.com",
  "rtbdemand.com",
  "rubiconproject.com",
  "runative-syndicate.com",
  "sharethrough.com",
  "smartadserver.com",
  "smartclip.net",
  "smaato.net",
  "sonobi.com",
  "sortable.com",
  "sovrn.com",
  "spotxchange.com",
  "springserve.com",
  "startappservice.com",
  "taboola.com",
  "tapad.com",
  "tapjoy.com",
  "teads.tv",
  "telaria.com",
  "tidaltv.com",
  "traficjunky.net",
  "tremorhub.com",
  "triplelift.com",
  "undertone.com",
  "unityads.unity3d.com",
  "vungle.com",
  "w55c.net",
  "yieldify.com",
  "yieldlab.net",
  "yieldmo.com",
  "yllix.com",
  "zedo.com",
  "zergnet.com",
];

export const TRACKER_HOSTS = [
  "2o7.net",
  "amplitude.com",
  "analytics.google.com",
  "analytics.tiktok.com",
  "analytics.twitter.com",
  "appdynamics.com",
  "atinternet.com",
  "bat.bing.com",
  "bluekai.com",
  "chartbeat.com",
  "clarity.ms",
  "clck.yandex.ru",
  "clicky.com",
  "comscore.com",
  "connect.facebook.net",
  "ct.pinterest.com",
  "demdex.net",
  "facebook.net",
  "fullstory.com",
  "gemius.pl",
  "google-analytics.com",
  "googletagmanager.com",
  "heap.io",
  "hm.baidu.com",
  "hotjar.com",
  "id5-sync.com",
  "inspectlet.com",
  "kissmetrics.com",
  "krxd.net",
  "liveintent.com",
  "lotame.com",
  "luckyorange.com",
  "matomo.cloud",
  "mc.yandex.ru",
  "mixpanel.com",
  "ml314.com",
  "mouseflow.com",
  "newrelic.com",
  "nr-data.net",
  "omtrdc.net",
  "pixel.facebook.com",
  "piwik.pro",
  "px.ads.linkedin.com",
  "quantcast.com",
  "scorecardresearch.com",
  "segment.com",
  "segment.io",
  "smartlook.com",
  "statcounter.com",
  "top.mail.ru",
];
