"use strict";
// Classic-script data for content scripts (content scripts cannot use ES imports).
globalThis.AuraAdBlockRules = Object.freeze({
  COSMETIC_SELECTORS: Object.freeze([
    'ins.adsbygoogle',
    '[data-ad-client]',
    '[data-ad-slot]',
    '[data-ad-format]',
    '[id^="google_ads"]',
    '[id^="ad-"]',
    '[id^="ads-"]',
    '[id*="adslot"]',
    '[id*="ad-slot"]',
    '[class^="ad-"]',
    '[class^="ads-"]',
    '[class*="ad-container"]',
    '[class*="ad-banner"]',
    '[class*="ad-slot"]',
    '[class*="ad-wrapper"]',
    '[class*="ad-panel"]',
    '[class*="advertisement"]',
    '[class*="advert"]',
    '[class*="sponsored"]',
    '[class*="promoted"]',
    '[class*="taboola-"]',
    '[class*="outbrain"]',
    '.ad-box',
    '.ad-unit',
  ]),
  ANNOYANCE_SELECTORS: Object.freeze([
    '[class*="popup"]',
    '[id*="popup"]',
    '[class*="modal"]',
    '[id*="modal"]',
    '[class*="overlay"]',
    '[id*="overlay"]',
    '[class*="lightbox"]',
    '[id*="lightbox"]',
    '[class*="cookie-banner"]',
    '[class*="cookieBanner"]',
    '[class*="cookie-notice"]',
    '[class*="consent"]',
  ]),
  DEFAULT_SETTINGS: Object.freeze({
    enabled: true,
    filters: Object.freeze({ ads: true, trackers: true, annoyances: false }),
    siteAllow: Object.freeze([]),
  }),
});
