export const gogoanimeRegressions = Object.freeze([
  Object.freeze({
    id: "gogoanime-futsutsuka-episode-8-blogger-progressive",
    liveUrl: "https://gogoanime.by/futsutsuka-na-akujo-dewa-gozaimasu-ga-suuguu-chouso-torikae-den-episode-8-english-subbed/",
    recommendedAdblockMode: "on",
    settleMs: 8_000,
    expected: Object.freeze({
      primaryHost: "rr4---sn-npoe7nl6.googlevideo.com",
      livePrimaryHostFlexible: true,
      primaryHostSuffix: ".googlevideo.com",
      primaryTitle: "Futsutsuka na Akujo dewa Gozaimasu ga: Suuguu Chouso Torikae Den Episode 8 English Subbed",
      rejectedPrimaryHosts: ["z6v2p9a8.bkcdn.net"],
    }),
    candidates: Object.freeze([
      Object.freeze({
        pageTitle: "Futsutsuka na Akujo dewa Gozaimasu ga: Suuguu Chouso Torikae Den Episode 8 English Subbed",
        pageUrl: "https://gogoanime.by/futsutsuka-na-akujo-dewa-gozaimasu-ga-suuguu-chouso-torikae-den-episode-8-english-subbed/",
        resourceUrl: "https://z6v2p9a8.bkcdn.net/library/834176/1342b400f1b83542546aec8bb73bc20d6b1329ba.mp4",
        contentType: "video/mp4", frameId: 0, source: "media-element", confidence: 100, main: true,
      }),
      Object.freeze({
        pageTitle: "Futsutsuka na Akujo dewa Gozaimasu ga: Suuguu Chouso Torikae Den Episode 8 English Subbed",
        pageUrl: "https://gogoanime.by/player/?source=blogger&url=encoded",
        siteUrl: "https://gogoanime.by/futsutsuka-na-akujo-dewa-gozaimasu-ga-suuguu-chouso-torikae-den-episode-8-english-subbed/",
        resourceUrl: "https://rr4---sn-npoe7nl6.googlevideo.com/videoplayback?id=blogger-video",
        contentType: "video/mp4",
        frameId: 228,
        source: "web-response",
        player: "",
        confidence: 70,
        main: true,
      }),
    ]),
  }),
  Object.freeze({
    id: "gogoanime-bleach-kashin-tan-episode-4-megaplay-hls",
    liveUrl: "https://gogoanime.by/bleach-sennen-kessen-hen-kashin-tan-episode-4-english-subbed/",
    recommendedAdblockMode: "on",
    settleMs: 8_000,
    expected: Object.freeze({
      primaryHost: "megaplay.su",
      primaryPlayer: "player-page",
      livePrimaryHosts: ["megaplay.su", "googlevideo.com"],
      rejectedPrimaryHosts: ["z6v2p9a8.bkcdn.net"],
    }),
    candidates: Object.freeze([
      Object.freeze({
        pageTitle: "Bleach: Sennen Kessen-hen - Kashin-tan Episode 4 English Subbed - Gogoanime",
        pageUrl: "https://megaplay.su/embed.php?sid=ZlhkYzgwME1oTExDTlc2WmlyQjhxZz09",
        siteUrl: "https://gogoanime.by/bleach-sennen-kessen-hen-kashin-tan-episode-4-english-subbed/",
        resourceUrl: "https://megaplay.su/uploads/hls/ZlhkYzgwME1oTExDTlc2WmlyQjhxZz09/index.m3u8?v=1786810514",
        contentType: "application/vnd.apple.mpegurl",
        frameId: 2,
        source: "player-page-resolver",
        player: "player-page",
        confidence: 100,
        main: true,
      }),
    ]),
  }),
]);
